name: Build Anyo
on: [push]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Generate Xcode project
        run: |
          brew install xcodegen
          xcodegen generate
      - name: Build
        run: xcodebuild build -project Anyo.xcodeproj -scheme Anyo -destination 'platform=iOS Simulator,name=iPhone 15' -skipPackagePluginValidation
